### ISSUE TITLE
Use existing tor install, "external" host does not work.

### ISSUE THREAD

**Issue by Napsterbater** [BiglySoftware/BiglyBT-plugin-aznettor#1]
```
Testing connection via SOCKS proxy on port 9100
Test failed: Malformed reply from SOCKS server
```
I can use the TOR Socks Proxy on that host with the set IP and Port with Firefox and other apps just fine.

But setting that IP and port in the plugin and test results in the above.

The tor host is a Ubuntu 20.04.2 LTS with Tor Tor 0.4.5.9

**Comment by parg** [comment]
Works fine for me - the response you're getting is the one I get when the Tor service isn't actually running on the specified host/port

**Comment by Napsterbater** [comment]
As you can see from the 3 screenshots, I have set 10.0.0.42 as the socks host and port 9050.
Yet, Bigly/TorPlugin is trying to connect to 127.0.0.1:9050, it is ignoring the host I have set.

BiglyBT 2.8.0.1_B12 (though this has been broken for many many versions) is running on a Windows 2019 server with Java 8 u271

![Capture](https://user-images.githubusercontent.com/18711451/130530475-4556dd28-476c-470b-a664-e3c61b15c314.PNG)
![Capture2](https://user-images.githubusercontent.com/18711451/130530478-68705cc1-16cc-4ae7-8f56-bf7244cbc077.PNG)
![Capture3](https://user-images.githubusercontent.com/18711451/130530490-622ccdf9-cdb3-4edc-96dc-f56311be871d.PNG)

**Comment by parg** [comment]
Ah, there's a bug whereby on startup the values for the external host/port are not being setup. You should find that changing them once BiglyBT is running will work though, just not after a restart of BiglyBT.

**Comment by parg** [comment]
I release plugin version 1.2.8 for Windows with a fix - please tell me if it works.

**Comment by Napsterbater** [comment]
Works perfectly now. Thanks.
